### ISSUE TITLE
Not an issue just a suggestion

### ISSUE THREAD

**Issue by Stevemoretz** [tylernathanreed/laravel-relation-joins#12]
This is rally impressive, I'd suggest you propose this becomes a part of laravel itself, this is for sure the missing peice of eloquent and laravel.

**Comment by tylernathanreed** [comment]
I'm glad you think so!

I tried this with a past version of the package, and I received some push back. I think that because my solution exists as a package, the contributors would rather have the community use the package, as opposed to natively integrate the package into the framework.

There are a lot of interpretations out there as to how relation joining should be done, and I think that friction is why it's probably best to keep this as a package.

I wouldn't be against someone recommending my package to the Laravel framework contributors, but I won't be doing that myself.
