### ISSUE TITLE
latestOfMany? 

### ISSUE THREAD

**Issue by Vasiliy-Makogon** [tylernathanreed/laravel-relation-joins#19]
Hi. I have method with latestOfMany:

```
class OIOrder ....
    public function legalEntityOIOrderProcessingStatus(): HasOne
    {
        return $this->hasOne(
            LegalEntityOIOrderProcessingStatus::class,
            'oi_order_id',
            'id'
        )->latestOfMany();
    }
```

It's dont work with tis package :(

```
$query->joinRelation('legalEntityOIOrderProcessingStatus');
```

```
select `oi_order`.*
from `oi_order`
         inner join `legal_entity_oi_order` on `legal_entity_oi_order`.`oi_order_id` = `oi_order`.`id`
         inner join `legal_entity` on `legal_entity`.`id` = `legal_entity_oi_order`.`legal_entity_id`
         inner join `legal_entity_oi_order_processing_status_log` on `legal_entity_oi_order_processing_status_log`.`oi_order_id` = `oi_order`.`id` and
          `legal_entity_oi_order_processing_status_log`.`deleted_at` is null
where 
    `legal_entity`.`user_id` = ? and 
    `oi_order`.`deleted_at` is null
```

I expected it to do a join by condition latestOfMany :(

**Comment by tylernathanreed** [comment]
Joining into a hasOne or hasOneThrough relation requires only one record to be found.

There is technically a way to solve for the "latestOfMany" scenario, but it would significantly tank query performance. Here's what the SQL would look like:

```sql
select `oi_order`.*
from `oi_order`
    inner join (
        select *
        from (
            select
                `legal_entity_oi_order_processing_status_log`.*,
                row_number() over(
                    partition by `legal_entity_oi_order_processing_status_log`.`oi_order_id`
                    order by `legal_entity_oi_order_processing_status_log`.`id` desc
                ) as `latest_of_many_ordinal`
            from `legal_entity_oi_order_processing_status_log`
            where `legal_entity_oi_order_processing_status_log`.`oi_order_id` = `oi_order`.`id`
                and `legal_entity_oi_order_processing_status_log`.`deleted_at` is null
        ) as `legal_entity_oi_order_processing_status_log`
        where `latest_of_many_ordinal` = 1
    ) as `legal_entity_oi_order_processing_status_log`
where `legal_entity`.`user_id` = ? and 
    `oi_order`.`deleted_at` is null
```

As you can see, this requires a double-nested sub select on a join with a partition. These are _incredibly_ slow to execute when your data set begins to scale (this is on the scale of taking minutes instead of milliseconds).

The more performant approach would be to add a new `latest_legal_entity_oi_order_processing_status_log_id` column to your `oi_order` table, and join on it using a `belongsTo` relation. You'd need to maintain that column through observers or otherwise to keep it up to date.

While I could probably find some way to make a `latestOfMany` join work out of the box, I can't condone the significant performance impacts, and would rather you seek an alternative, such as the one I outlined above.
